[package]
name = "rustracer"
version = "0.1.0"
edition = "2021"

[dependencies]
softbuffer = "0.3"
winit = "0.28"
rayon = "1.10"
rand = { version = "0.8", features = ["small_rng"] }
image = "0.25"
tobj  = "4"
oidn  = { version = "2", optional = true }

[features]
denoise = ["dep:oidn"]

[profile.release]
opt-level       = 3
lto             = "fat"
codegen-units   = 1
panic           = "abort"

[profile.dev]
opt-level       = 1

